app:
  name: Kultpower.org
  resources: /Users/sebastian/www/springboot/ #Folder with external content

debug:  true

# DataSource settings: set here your own configurations for the database
# connection.
spring:
  datasource:
    url:  jdbc:hsqldb:mem:oregami;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;characterEncoding=UTF-8
    #url:  jdbc:mysql://localhost:3306/oregami?useUnicode=true&characterEncoding=UTF-8
    #username: oregami
    #password: oregami
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle:  true
    alidationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: create
      dialect:  org.hibernate.dialect.HSQLDialect
      #dialect:  org.hibernate.dialect.MySQL5Dialect
      naming-strategy:  org.hibernate.cfg.EJB3NamingStrategy

    properties:
      hibernate:
        dialect:  org.hibernate.dialect.HSQLDialect
        #dialect:  org.hibernate.dialect.MySQL5Dialect
      jadira:
        usertype:
          autoRegisterUserTypes: true

    show-sql: true


  thymeleaf:
    cache: false

logging:
  level:
    org.springframework.web:  DEBUG
    org.springframework.transaction:  DEBUG
    org.springframework.boot: OFF

liquibase.:
  #changeLog: classpath:/db/changelog/db.changelog-master.xml
  changeLog: classpath:/liquibase/master.xml
