# DataSource settings: set here your own configurations for the database
# connection. In this example we have "netgloo_blog" as database name and
# "root" as username and password.
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/oregami?useUnicode=true&characterEncoding=UTF-8
#CREATE DATABASE `oregami` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;
#CREATE USER 'oregami'@'localhost' IDENTIFIED BY 'oregami';
#GRANT ALL PRIVILEGES ON `oregami`.* TO 'oregami'@'localhost' WITH GRANT OPTION;
    username: oregami
    password: oregami

  jpa:
    hibernate:
      ddl-auto: create
      dialect:  org.hibernate.dialect.MySQL5Dialect

    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL5Dialect